# Generated by Django 6.0.4 on 2026-05-20 00:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Year 5, Primary 2B', max_length=100, unique=True)),
                ('academic_year', models.CharField(default='2026/2027', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('enquiry_type', models.CharField(choices=[('general', 'General Enquiry'), ('admissions', 'Admissions'), ('academics', 'Academics'), ('pastoral', 'Pastoral / Wellbeing'), ('absence', 'Report an Absence'), ('other', 'Other')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('staff_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('sports', 'Sports & Activities'), ('arts', 'Arts & Culture'), ('admissions', 'Admissions & Open Days'), ('parent', 'Parent Events'), ('holiday', 'Holidays & Closures'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProspectusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('child_name', models.CharField(max_length=150)),
                ('child_age_group', models.CharField(choices=[('early_years', 'Early Years (Ages 3–5)'), ('primary', 'Primary (Ages 5–11)'), ('middle', 'Middle School (Ages 11–14)'), ('senior', 'Senior School (Ages 14–18)')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Any specific questions or interests.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Prospectus Request',
                'verbose_name_plural': 'Prospectus Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code e.g. MATH, ENG', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_date_of_birth', models.DateField()),
                ('student_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], default='other', max_length=10)),
                ('proposed_entry_year', models.CharField(choices=[('2026/2027', '2026/2027 Academic Year'), ('2027/2028', '2027/2028 Academic Year')], max_length=10)),
                ('current_school', models.CharField(blank=True, max_length=200)),
                ('current_grade', models.CharField(blank=True, help_text='E.g., Year 4, Grade 3, etc.', max_length=50)),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_address', models.TextField(blank=True)),
                ('how_heard', models.CharField(blank=True, choices=[('website', 'School Website'), ('social_media', 'Social Media'), ('referral', 'Friend/Family Referral'), ('event', 'Open Day/Event'), ('advert', 'Advertisement'), ('other', 'Other')], max_length=20)),
                ('birth_certificate', models.FileField(blank=True, help_text="Upload a scan or photo of the student's birth certificate or passport.", null=True, upload_to='applications/birth_certificates/%Y/%m/')),
                ('last_report_card', models.FileField(blank=True, help_text='Upload the most recent school report (if applicable).', null=True, upload_to='applications/report_cards/%Y/%m/')),
                ('additional_document', models.FileField(blank=True, help_text='Any additional document (e.g., recommendation letter).', null=True, upload_to='applications/additional/%Y/%m/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview', 'Interview Scheduled'), ('offered', 'Offer Made'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('offer_response', models.CharField(blank=True, choices=[('accept', 'Accept'), ('decline', 'Decline')], max_length=10, null=True)),
                ('offer_response_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/')),
                ('summary', models.TextField(max_length=500)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classgroup')),
                ('user', models.OneToOneField(blank=True, help_text='Link to a user account for the student portal (optional)', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_class', models.CharField(blank=True, help_text="Optional custom name for this class (e.g. 'Year 5')", max_length=100)),
                ('academic_year', models.CharField(default='2026/2027', max_length=20)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_relationships', to='core.classgroup')),
                ('students', models.ManyToManyField(blank=True, related_name='class_relationships', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.AddField(
            model_name='classgroup',
            name='subjects',
            field=models.ManyToManyField(through='core.ClassRelationship', to='core.subject'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g. Mr, Mrs, Dr', max_length=10)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('class_taught', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='core.classgroup')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classrelationship',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to='core.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='classrelationship',
            unique_together={('class_group', 'subject')},
        ),
    ]
