# Generated by Django 6.0.4 on 2026-05-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrelationship',
            name='students',
        ),
    ]
