# Generated by Django 6.0.4 on 2026-05-20 01:21

from django.db import migrations, models


def copy_class_group_students_to_relationships(apps, schema_editor):
    ClassRelationship = apps.get_model('core', 'ClassRelationship')
    Student = apps.get_model('core', 'Student')

    for relationship in ClassRelationship.objects.all().iterator():
        student_ids = Student.objects.filter(
            class_group_id=relationship.class_group_id
        ).values_list('id', flat=True)
        relationship.students.set(student_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_classrelationship_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrelationship',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_relationships', to='core.student'),
        ),
        migrations.RunPython(
            copy_class_group_students_to_relationships,
            migrations.RunPython.noop,
        ),
    ]
