# Generated by Django 6.0.4 on 2026-05-20 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classrelationship_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrelationship',
            name='students',
        ),
        migrations.AddField(
            model_name='classrelationship',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_relationships', to='core.student'),
        ),
    ]
