# Generated by Django 6.0.4 on 2026-05-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_classrelationship_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrelationship',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='class_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classrelationship'),
        ),
    ]
