# Generated by Django 6.0.4 on 2026-05-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_classrelationship_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_relationship',
        ),
        migrations.AddField(
            model_name='classrelationship',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_relationships', to='core.student'),
        ),
    ]
