# Generated by Django 6.0.4 on 2026-05-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_student_class_relationship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrelationship',
            name='students',
        ),
    ]
